### PR TITLE
fix defunct container-shim

### PR DESCRIPTION
**Pull request by mengzhuo**
This PR fix dind won't reap child container as they quit which will create a lots of defunct processs for host.

### CODE REVIEW

**Comment by tchiotludo** [comment]
Hey, can you share what is happening? 
We don't see any issues on our side?
Maybe you can share the cloud provider for your kubernetes and some information about the hosting?

**Comment by mengzhuo** [comment]
Our K8S cluster using hosted on an old linux kernel ( <4.19 ) which has no cgroup v2 support and causing fuse-overlayfs can't be reap properly.

**Comment by tchiotludo** [comment]
maybe in that case it can be better to add an extraEnv for dind on our helm charts, and let people doing what they want?

**Comment by tchiotludo** [comment]
@mengzhuo : https://github.com/kestra-io/helm-charts/commit/875711bea10700851c799c6f480ff3226b8c327b with that you will be able to add any env, reopen if you think there is a largest issues on dind we don't see

**Pull request closed without merging**
